name: Publish Docker image

on:
  push:
    branches: ['*']
  release:
    types: [published]

jobs:
  build-and-push:
    name: Build Docker image and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: noamtm/kafka-kraft
          tags: |
            type=ref,event=branch,prefix=_
            type=semver,event=tag,pattern={{version}}
            type=sha

      - name: Build and push Docker image (release)
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          # Push only if tag or default branch
          push: ${{ github.event_name == 'release' || github.ref_name == github.event.repository.default_branch }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
